export const ANGLICISM_MAP: Record<string, string[]> = {
  cloud: ["nuvem"],
  web: ["site", "página", "pagina", "internet"],
  software: ["sistema", "programa"],
  data: ["dados"],
  database: ["banco", "dados"],
  storage: ["armazenamento"],
  network: ["rede", "redes"],
  hardware: ["máquina", "maquina", "computador"],
  security: ["segurança", "seguranca"],
  privacy: ["privacidade"],
  design: ["design"],
  marketing: ["marketing"],
  branding: ["marca"],
  ux: ["experiência", "experiencia", "usuário", "usuario"],
  ui: ["interface"],
  api: ["api", "integração", "integracao"],
  dev: ["desenvolvimento", "desenvolvedor"],
  developer: ["desenvolvedor", "desenvolvimento"],
  code: ["código", "codigo", "desenvolvimento"],
  frontend: ["front", "interface", "web"],
  backend: ["back", "api", "servidor"],
  fullstack: ["desenvolvimento"],
  saas: ["software", "sistema", "nuvem"],
  ai: ["inteligência", "inteligencia", "ia"],
  ml: ["inteligência", "inteligencia", "ia"],
  analytics: ["análise", "analise", "dados"],
  audit: ["auditoria"],
  consulting: ["consultoria"],
  automation: ["automação", "automacao"],
  drone: ["drone", "piloto"],
  photography: ["fotografia", "foto"],
  video: ["vídeo", "video", "filmagem"],
  music: ["música", "musica", "produção"],
  event: ["evento", "festa"],
  wedding: ["casamento", "evento"],
  burger: ["hambúrguer", "hamburguer"],
  food: ["alimentação", "alimentacao", "comida"],
  yoga: ["yoga"],
  meditation: ["meditação", "meditacao"],
  therapy: ["terapia", "psicologia"],
  counseling: ["psicologia", "terapia"],
  psychology: ["psicologia"],
  nutrition: ["nutrição", "nutricao", "nutricional"],
  elder: ["idoso", "cuidado"],
  elderly: ["idoso", "cuidado"],
  school: ["ensino", "escolar"],
  tutoring: ["reforço", "reforco", "ensino"],
  education: ["educação", "educacao", "ensino"],
  translate: ["tradução", "traducao"],
  translation: ["tradução", "traducao"],
  writing: ["escrita"],
  content: ["conteúdo", "conteudo"],
  fashion: ["moda", "stylist"],
  stylist: ["stylist", "moda"],
  drywall: ["drywall", "construção", "construcao"],
  construction: ["construção", "construcao"],
  agriculture: ["agro", "agrofloresta"],
  compost: ["compostagem"],
  art: ["arte", "artes"],
  graffiti: ["grafite"],
  mural: ["mural", "fachada"],
};

export function expandQuery(tokens: string[]): string[] {
  const out = new Set(tokens);
  for (const t of tokens) {
    const synonyms = ANGLICISM_MAP[t];
    if (synonyms) synonyms.forEach(s => out.add(s));
  }
  return [...out];
}
