titulo: Tradução PT-Guarani
parent: Tradução
implicitResponsavel:
  - denise
paraQuem: Português → Guarani
digital: true
hoursLow: 0.003
hoursHigh: 0.005
unit: palavra
cnae:
  - c: 7490-1/01
    d: Serviços de tradução, interpretação e similares
