/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar entries por tipo */
        get: {
            parameters: {
                query?: {
                    type?: "servico" | "missao" | "membro" | "comunidade" | "garden" | "relato" | "ref" | "proj" | "node" | "doc";
                    /** @description Full-text search */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de entries */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            entries?: (components["schemas"]["Person"] | components["schemas"]["Community"] | components["schemas"]["Service"])[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-sincronizar após edição local */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reindexed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Identificador único de pessoa, comunidade ou business.
         * @example yuri
         * @example quilomboaraucaria
         * @example retro-umarizal
         */
        Handle: string;
        /** @enum {string} */
        EntityType: "person" | "business" | "community" | "reference";
        /** @enum {string} */
        Tag: "fundador" | "parceiro" | "comunidade" | "em-memoria" | "em-breve" | "guardiao" | "familia" | "menor" | "referencia" | "aposentado" | "contabilidade" | "alimentacao";
        Citacao: {
            texto: string;
            autor?: components["schemas"]["Handle"];
            /** @description Nome do autor quando ele não é uma entity registrada. */
            autorNome?: string;
            autorEmBreve?: {
                title?: string;
            };
            obra?: string;
            /** @description ISO-8601 OU ano só ("2015") OU date-time. Free-form pra acomodar citações imprecisas. */
            data?: string;
            /** Format: uri */
            url?: string;
        };
        HomeLink: {
            label: string;
            /** @description URL or path (used by Person.homeLinks). */
            url?: string;
            /** @description URL or path (used by Solution.homeLinks). */
            href?: string;
        };
        /** @description Poema autoral. Renderizado em `/<autor>/<slug>/`. */
        PortfolioPoem: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "poem";
            /** @description URL-safe slug. Compõe `/<autor>/<slug>/`. */
            slug: string;
            titulo: string;
            /** @description Handle do autor (quando diferente do dono do portfolio). */
            autor?: components["schemas"]["Handle"];
            /** @description Lista de estrofes; cada estrofe é lista de linhas. */
            stanzas: string[][];
            /**
             * @description Se true, não renderizado publicamente. Útil enquanto texto está em produção.
             * @default false
             */
            draft: boolean;
        };
        /** @description Ensaio em prosa. Renderizado em `/<autor>/<slug>/`. */
        PortfolioEssay: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "essay";
            slug: string;
            titulo: string;
            /** @description Resumo (1-3 frases) pra teaser. */
            short?: string;
            /** @description Markdown multi-linha (literal block scalar `|`). */
            body?: string;
            /** @default false */
            draft: boolean;
        };
        /** @description Item autoral (poema, ensaio, etc). Discriminator é `kind`. */
        PortfolioItem: components["schemas"]["PortfolioPoem"] | components["schemas"]["PortfolioEssay"];
        Contacts: {
            tagline?: string;
            /** Format: email */
            email?: string;
            whatsapp?: string;
            /** @description Número formatado para exibição (ex "+55 11 98371-7331"). */
            whatsappDisplay?: string;
            /** @description Nome de usuário Instagram (sem @). */
            instagram?: string;
            /** Format: uri */
            site?: string;
        };
        Person: {
            handle: components["schemas"]["Handle"];
            /** @enum {string} */
            type: "person" | "business" | "reference";
            nome: string;
            /** @description Função/papel curto (ex "Sementes", "Comunicação"). */
            role?: string;
            tags?: components["schemas"]["Tag"][];
            /** @description Caminho relativo da foto (ex "/yuri/yuri.jpg"). */
            pic?: string | null;
            /** @description ISO-8601, date OR date-time. Date-only (1957-03-15) é válido pra registros históricos sem hora; date-time (1993-06-24T12:30:00-03:00) pra registros precisos. */
            birthDate?: string & (unknown | unknown);
            bioTitle?: string;
            /** @description Resumo curto da bio. Soft-cap 280 chars (recomendado pra teaser); não enforced. */
            bioCurta?: string;
            /** @description Markdown inline (links, ênfases). Multi-linha via `\|` literal. */
            bio?: string;
            citacoes?: components["schemas"]["Citacao"][];
            servicos?: string[];
            subMembers?: components["schemas"]["Handle"][];
            communities?: components["schemas"]["Handle"][];
            contacts?: components["schemas"]["Contacts"];
            homeLinks?: components["schemas"]["HomeLink"][];
            /** @description Itens autorais (poemas, ensaios). Cada um renderizado em `/<handle>/<slug>/`. */
            portfolio?: components["schemas"]["PortfolioItem"][];
            /** @description ISO-8601 date (YYYY-MM-DD). Presente apenas para pessoas falecidas. */
            deathDate?: string;
            /** @description Trecho oculto da bio (revelado via <details>). Não indexado. */
            bioHidden?: string;
            /** @description Caminho relativo do arquivo de áudio da bio (ex "/alice/alice.ogg"). */
            bioAudio?: string;
            /** @description URL do site pessoal ou projeto (diferente do externalUrl que é redirect). */
            site?: string;
            /** @description Título da seção de ensaios no perfil. */
            essaysTitle?: string;
            /** @default false */
            emMemoria: boolean;
            /**
             * @description Perfil em construção — conteúdo ainda não publicado.
             * @default false
             */
            emBreve: boolean;
            /**
             * @description Membro aposentado (sócio que saiu mas permanece na rede).
             * @default false
             */
            aposentado: boolean;
            /**
             * @description Menor de idade — renderizado com restrições.
             * @default false
             */
            underage: boolean;
            /**
             * @description Não exibido na listagem pública mas acessível por URL direta.
             * @default false
             */
            muted: boolean;
            /** @default false */
            referenceOnly: boolean;
            /** @description URL externa OU path relativo (`/retro-umarizal/`). Pra type=business com site próprio ou redirect interno. */
            externalUrl?: string;
        };
        Parceria: {
            de: components["schemas"]["Handle"];
            /** @enum {string} */
            tipo: "pro-bono" | "paga" | "troca";
            descricao?: string;
            contribuicoes?: {
                quem: components["schemas"]["Handle"];
                oque: string;
            }[];
        };
        Community: {
            handle: components["schemas"]["Handle"];
            /** @enum {string} */
            type: "community";
            nome: string;
            role?: string;
            tags?: components["schemas"]["Tag"][];
            pic?: string | null;
            tagline?: string;
            /** @description Resumo curto da bio. Soft-cap 280 chars. */
            bioCurta?: string;
            bio?: string;
            /** Format: uri */
            externalUrl?: string;
            /** Format: uri */
            site?: string;
            servicos?: string[];
            membros?: components["schemas"]["Handle"][];
            parcerias?: components["schemas"]["Parceria"][];
            /**
             * @description UI hint pro renderer.
             * @default false
             */
            sectionBreak: boolean;
            /**
             * @description Não exibido na listagem pública mas acessível por URL direta.
             * @default false
             */
            muted: boolean;
            /**
             * @description Perfil em construção — conteúdo ainda não publicado.
             * @default false
             */
            emBreve: boolean;
            /**
             * @description Comunidade encerrada / em memória.
             * @default false
             */
            emMemoria: boolean;
        };
        CnaeEntry: {
            /** @description Código CNAE (ex 6202-3/00). */
            c: string;
            /** @description Descrição. */
            d: string;
        };
        Service: {
            titulo: string;
            /** @description Auto-derived from titulo via slugify(). */
            slug?: string;
            /** @description Titulo do parent service (sub-services). */
            parent?: string;
            /** @description Audience tagline (ex "Empresas · estúdios"). Hoje hidden no card. */
            paraQuem?: string;
            /** @default false */
            digital: boolean;
            /** @default false */
            recurring: boolean;
            hoursLow?: number;
            hoursHigh?: number;
            /** @enum {string} */
            unit?: "hora" | "palavra" | "pessoa" | "unidade" | "aula" | "sessão" | "oficina" | "torta" | "diária" | "treino" | "grupo" | "consulta";
            /** @description Derived. Quem oferece o service. */
            responsavel?: components["schemas"]["Handle"][];
            /** @description Sub-services herdam responsibility do parent. */
            implicitResponsavel?: components["schemas"]["Handle"][];
            cnae?: components["schemas"]["CnaeEntry"][];
            /** @default false */
            cnaeNovo: boolean;
            /**
             * @description If true, not shown in /servicos/ (personal/family relations).
             * @default false
             */
            hidden: boolean;
            /** @description Nome de exibição alternativo ao titulo (ex versão abreviada). */
            nome?: string;
            /** @description Copy próprio descrevendo como entregamos o serviço (≠ descrição CNAE genérica). */
            descNossa?: string;
            /** @description Resumo curto do serviço para cards e listagens. */
            summary?: string;
            /** @description Derived. Títulos de sub-serviços cujo parent é este serviço. */
            children?: string[];
            /** @description Named pricing plans for this service. */
            planos?: components["schemas"]["ServicePlan"][];
            attachments?: components["schemas"]["Attachment"][];
        };
        ServicePlan: {
            label?: string;
            hours?: number;
            unit?: string;
        };
        Attachment: {
            label: string;
            url: string;
            /** @enum {string} */
            kind: "pdf" | "link";
        };
        Platform: {
            name: string;
            /** @enum {string} */
            status: "done" | "wip";
            statusText?: string;
        };
        Mission: {
            handle: components["schemas"]["Handle"];
            /** @enum {string} */
            type: "mission";
            nome: string;
            subtitle?: string;
            comunidade: components["schemas"]["Handle"];
            objetivo?: string;
            objetivoAutor?: components["schemas"]["Handle"];
            tags?: string[];
            servicos?: string[];
            envolvidos?: components["schemas"]["Handle"][];
            parentMission?: components["schemas"]["Handle"];
            attachments?: components["schemas"]["Attachment"][];
        };
        Solution: {
            handle: components["schemas"]["Handle"];
            /** @enum {string} */
            type: "solution";
            nome: string;
            tagline?: string;
            url?: string;
            urlLabel?: string;
            /** @default false */
            internalLink: boolean;
            externalUrl?: string;
            lema?: string;
            desc?: string;
            /** @description Long-form description (markdown-lite). */
            descLong?: string;
            /** @enum {string} */
            lifecycle: "active" | "futuro";
            /** @default false */
            universo: boolean;
            comunidade?: components["schemas"]["Handle"];
            /** @description ISO-8601 date string. */
            releaseDate?: string;
            /** @description "*" for all services, or array of service titles. */
            bundledServices?: "*" | string[];
            platforms?: components["schemas"]["Platform"][];
            homeLinks?: components["schemas"]["HomeLink"][];
        };
        FinanceCost: {
            key: string;
            label: string;
            value: number;
            detail?: string;
            breakdown?: {
                label: string;
                value: number;
                handle?: components["schemas"]["Handle"];
            }[];
        };
        FinanceRecurrentItem: {
            label: string;
            client?: string;
            detail?: string;
            responsavel: components["schemas"]["Handle"];
            mensal: number;
            solucoes?: components["schemas"]["Handle"][];
        };
        FinanceRampaItem: {
            label: string;
            client?: string;
            detail?: string;
            responsavel: components["schemas"]["Handle"];
            meses: {
                mes: string;
                value: number;
            }[];
            solucoes?: components["schemas"]["Handle"][];
        };
        FinanceProject: {
            label: string;
            detail?: string;
            unitValue: number;
            unidades: number;
            responsavel?: components["schemas"]["Handle"];
            solucoes?: components["schemas"]["Handle"][];
        };
        FinanceProBono: {
            label: string;
            detail?: string;
            responsavel: components["schemas"]["Handle"];
            solucoes?: components["schemas"]["Handle"][];
        };
        Finances: {
            currency: string;
            quarter: string;
            metaMensal?: number;
            metaQ2: number;
            custos: components["schemas"]["FinanceCost"][];
            receita: {
                recorrenteMensal: components["schemas"]["FinanceRecurrentItem"][];
                rampa: components["schemas"]["FinanceRampaItem"][];
                projetos: components["schemas"]["FinanceProject"][];
                proBono: components["schemas"]["FinanceProBono"][];
            };
        };
        /** @description Referência reversa — indica que `from` menciona o handle alvo. */
        BacklinkEntry: {
            /** @description Handle ou slug da entidade que referencia. */
            from: string;
            /** @description Nome de exibição da entidade que referencia. */
            nome: string;
            /**
             * @description Tipo da entidade que referencia.
             * @enum {string}
             */
            type: "person" | "community" | "service" | "mission" | "solution";
            /** @description Campo pelo qual a referência é feita (ex. "membros", "responsavel"). */
            via: string;
        };
        /** @description Mapa de handle → lista de referências reversas. Gerado por bake-backlinks.mjs em assets/backlinks.json. */
        BacklinkIndex: {
            [key: string]: components["schemas"]["BacklinkEntry"][];
        };
        /** @description Shape do `window.AL` exposed pelo renderer (data.js). */
        UniverseData: {
            people: components["schemas"]["Person"][];
            communities: components["schemas"]["Community"][];
            services: components["schemas"]["Service"][];
            DEFAULT_LOCATION?: {
                estado?: string;
                cidade?: string;
                bairro?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
