titulo: Produção Musical
paraQuem: Artistas · marcas
hoursLow: 8
hoursHigh: 20
cnae:
  - c: 9001-9/02
    d: Produção musical
  - c: 5920-1/00
    d: Atividades de gravação de som e de edição de música
